#!/usr/bin/env bash

while ! curl -s http://localhost:9222/json/version > /dev/null; do
    sleep 0.1
done

# Get the websocket url
export WS_URL=$(curl -s http://localhost:9222/json/version | jq -r '.webSocketDebuggerUrl')
echo $WS_URL
